# Generated by Django 3.2.13 on 2022-05-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='region',
            field=models.CharField(choices=[('kur', 'Kurdistan'), ('irq', 'Iraq')], default='irq', max_length=10),
            preserve_default=False,
        ),
    ]
