# Generated by Django 3.2.13 on 2022-05-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_auto_20220517_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['-region', 'name']},
        ),
        migrations.AddField(
            model_name='site',
            name='category',
            field=models.CharField(choices=[('accommodation', 'Accommodation'), ('airport', 'Airport'), ('archaeology', 'Archaeology'), ('historic', 'Historic'), ('memorial', 'Memorial'), ('museum', 'Museum'), ('nature', 'Nature'), ('recreation', 'Recreation'), ('religious', 'Religious'), ('restaurant', 'Restaurant'), ('shopping', 'Shopping'), ('tea_shop', 'Tea Shop')], default='nature', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='primary_attraction',
            field=models.BooleanField(default=False),
        ),
    ]
