# Generated by Django 3.2.13 on 2022-05-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_auto_20220521_1531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site',
            new_name='Sight',
        ),
    ]
