# Generated by Django 3.2.13 on 2024-06-01 14:49

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0007_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(default=None, null=True)),
                ('headline', models.CharField(max_length=255)),
                ('plan', tinymce.models.HTMLField()),
                ('hotel', models.CharField(max_length=255)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='itineraries.itinerary')),
                ('overnight_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overnight', to='destinations.destination')),
            ],
            options={
                'ordering': ['itinerary', 'day_number'],
            },
        ),
    ]
