# Generated by Django 3.2.13 on 2024-06-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_tour'),
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryday',
            name='destinations',
            field=models.ManyToManyField(related_name='daily_destinations', to='destinations.Destination'),
        ),
    ]
