# Generated by Django 3.2.13 on 2024-06-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_itineraryday_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
