# Generated by Django 3.2.13 on 2022-05-22 13:53

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0006_rename_site_sight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='no-image.png', unique=True, upload_to=gallery.models.upload_to)),
                ('caption', models.CharField(max_length=250)),
                ('is_visible', models.BooleanField(default=True)),
                ('sight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.sight')),
            ],
            options={
                'ordering': ['sight__name', 'image'],
            },
        ),
    ]
