# Generated by Django 3.2.13 on 2022-05-26 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['sight__destination', 'sight__name', 'image']},
        ),
    ]
