# Generated by Django 3.2.13 on 2022-05-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_rename_site_sight'),
        ('contact', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='destinations',
        ),
        migrations.AddField(
            model_name='contact',
            name='destinations',
            field=models.ManyToManyField(blank=True, related_name='contact_destinations', to='destinations.Destination'),
        ),
    ]
