# Generated by Django 3.2.13 on 2022-07-30 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20220716_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='num_days',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='num_guests',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(21)]),
        ),
    ]
