# Generated by Django 3.2.13 on 2024-05-16 13:30

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20220730_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='country',
            field=django_countries.fields.CountryField(default='IE', max_length=2),
            preserve_default=False,
        ),
    ]
