# Generated by Django 3.2.13 on 2022-05-21 19:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', tinymce.models.HTMLField()),
                ('category', models.CharField(choices=[('0', 'General Information'), ('1', 'Booking Information'), ('2', 'Pre-Departure'), ('3', 'Health & Safety'), ('4', 'Accommodation'), ('5', 'Food & Drink')], max_length=25)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'question'],
            },
        ),
    ]
